// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FCM
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFCMPackageString = "981616b2-7e7e-4ed6-bf04-26b395a53bbb";
        public static Guid guidFCMPackage = new Guid(guidFCMPackageString);

        public const string guidFCMUIRuleString = "69760bd3-80f0-4901-818d-c4656aaa08e9";
        public static Guid guidFCMUIRule = new Guid(guidFCMUIRuleString);

        public const string guidFCMPackageCmdSetString = "55165515-0f3b-4427-b4bc-5e023897d0cd";
        public static Guid guidFCMPackageCmdSet = new Guid(guidFCMPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FCMCommandId = 0x0100;
    }
}